defaults:
  - training
  - _self_

hydra:
  searchpath:
    - pkg://verl.trainer.config
  job:
    chdir: false

experiment:
  method: ppo
  test_file: null
  critic_alpha: 0.01
  critic_lambda: 0.99

data:
  train_files: null
  val_files: null
  train_batch_size: 16
  val_batch_size: 32
  validation_shuffle: false

actor_rollout_ref:
  actor:
    ppo_mini_batch_size: 16
    ulysses_sequence_parallel_size: 1
  rollout:
    n: 4
    log_prob_use_dynamic_bsz: false

trainer:
  total_training_steps: 30
  total_epochs: 100
  test_freq: 10
  save_freq: 30
  max_actor_ckpt_to_keep: 1
  max_critic_ckpt_to_keep: 1
  default_local_dir: null
  experiment_name: math-online
